# Global exclude:
exclude: '^data/,^build/,^dist/,^logs/,^outputs/,^results/,^.eggs/,^.dev/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    args: ['--markdown-linebreak-ext=md']
  - id: check-added-large-files
    args: ['--maxkb=1000']
  - id: check-ast
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: check-executables-have-shebangs
  - id: debug-statements
  - id: end-of-file-fixer
  - id: pretty-format-json
    args: ['--autofix', '--indent=4', '--no-sort-keys']
  - id: requirements-txt-fixer
    exclude: docs/requirements.txt
  - id: mixed-line-ending
    args: ['--fix=auto']

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3
    # args: [ "--force-exclude=dir/" ]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        files: "^src/"
        args: [--config-file=mypy.ini]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.5
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml", "-q", "-lll"]
    additional_dependencies: ["bandit[toml]"]
